### ISSUE TITLE
question: is claim-restriction possible

### ISSUE THREAD

**Issue by drzraf** [pjeby/oidc-sso#1]
I'd like to use this plugin in order to let members of a team connect to WP based on their GSuite account.
That means solely allowing users having an @myteam.com (google-based) Gsuite account able to register/connect.
Is it possible via UI? via hook? not at all? planned?

Thank you!

**Comment by pjeby** [comment]
Yes.  The [`oidc_sso_userdata`](https://github.com/dirtsimple/oidc-sso/blob/master/src/Identity.php#L57) filter can be trapped to deny access by doing an `exit` after displaying an error page or redirecting.  It's called every time a user logs in or registers, and it happens before the user record is created or updated, so if you trap there you can keep the user from being created in the first place.

The `$data` parameter has an `email` key that contains whatever value you've configured to be used as the email, so you can check that.  You can also use the second filter parameter, an `Identity` instance, to obtain any other values you like from the `id_claim` or `userinfo()`.

(Sorry for the slow reply; apparently Github was not subscribing me to notifications from my new repos; I just happened on this issue by chance today!)

**Comment by drzraf** [comment]
I guess they are sensibly similar to openid-connect-generic's [openid-connect-generic-user-login-test](https://github.com/daggerhart/openid-connect-generic/blob/dev/includes/openid-connect-generic-client.php#L386) and [openid-connect-generic-user-creation-test](https://github.com/daggerhart/openid-connect-generic/blob/dev/includes/openid-connect-generic-client-wrapper.php#L697)

Thank you for the answer!
